## TensorFlow 2 quickstart for Beginners

This is an example notebook from the [TensorFlow Documentation](https://github.com/tensorflow) to test our Tensorflow-2.18.0-jupyter Apptainer image. This code is a short intro to using Keras to test a neural network on classifying images. 

The whole guide can be found at: https://github.com/tensorflow/docs/blob/master/site/en/tutorials/quickstart/beginner.ipynb

In [2]:
import tensorflow as tf
print("TensorFlow version:", tf.__version__)

from tensorflow.keras.layers import Dense, Flatten, Conv2D
from tensorflow.keras import Model

TensorFlow version: 2.18.0


In [7]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0
     

11490434/11490434 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step


In [8]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

/usr/local/lib/python3.11/dist-packages/keras/src/layers/reshaping/flatten.py:37: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [9]:
predictions = model(x_train[:1]).numpy()
predictions

array([[-0.71370924,  0.18640882, -0.12447868, -0.6045662 ,  0.1255234 ,
         0.7804634 ,  0.800589  , -0.91843075, -0.08043462,  0.12062007]],
      dtype=float32)

In [10]:
tf.nn.softmax(predictions).numpy()

array([[0.04406025, 0.1083835 , 0.07942303, 0.04914135, 0.10198141,
        0.19631696, 0.20030798, 0.03590355, 0.08299932, 0.10148259]],
      dtype=float32)

In [11]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [12]:
loss_fn(y_train[:1], predictions).numpy()

np.float32(1.6280248)

In [13]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [14]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - accuracy: 0.8565 - loss: 0.4968
Epoch 2/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - accuracy: 0.9554 - loss: 0.1530
Epoch 3/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - accuracy: 0.9666 - loss: 0.1111
Epoch 4/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - accuracy: 0.9732 - loss: 0.0877
Epoch 5/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - accuracy: 0.9773 - loss: 0.0741


In [15]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 0s - 1ms/step - accuracy: 0.9781 - loss: 0.0725


[0.07254467904567719, 0.9781000018119812]

In [16]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [17]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[2.1398670e-08, 4.3740919e-10, 4.8832144e-06, 1.1729341e-04,
        2.5605165e-10, 2.3335957e-07, 5.9896038e-12, 9.9985874e-01,
        1.1083886e-07, 1.8717845e-05],
       [4.2490964e-08, 1.8553257e-05, 9.9997318e-01, 6.3480829e-06,
        1.2821017e-15, 3.1755187e-07, 9.2327149e-08, 1.6942913e-13,
        1.4120128e-06, 2.4202848e-13],
       [1.6097371e-06, 9.9842167e-01, 9.1146569e-05, 3.1039742e-06,
        3.5103552e-05, 8.3749383e-06, 1.2900595e-05, 1.3254838e-03,
        9.8697594e-05, 1.8512859e-06],
       [9.9982327e-01, 1.1976362e-08, 4.9696893e-05, 1.3661790e-08,
        2.0483688e-07, 1.6328506e-06, 1.5137627e-05, 1.9851977e-05,
        1.3942755e-08, 9.0245478e-05],
       [1.9469067e-06, 1.2582513e-08, 8.3743353e-06, 1.6938584e-06,
        9.9198920e-01, 6.9046177e-07, 1.6103820e-07, 1.3051556e-04,
        8.0706268e-06, 7.8593753e-03]], dtype=float32)>